name: Python Style Checker

# This workflow is triggered by a PR
# Simplified -> on: [pull_request]
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 2 * * 1-5"

jobs:
  style-job:
    runs-on: ubuntu-latest
    steps:
      - uses: andymckay/pycodestyle-action@0.1.3
